version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-container
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sa
      MYSQL_DATABASE: users
      MYSQL_USER: admin
      MYSQL_PASSWORD: sa
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: my-phpmyadmin-container
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: admin
      PMA_PASSWORD: sa
    ports:
      - "443:80"
    depends_on:
      - mysql
volumes:
  mysql_data: